FROM python:3.8.8-slim
RUN apt-get update && apt-get install -y ffmpeg && apt-get clean
RUN pip install spleeter numpy==1.18.5 essentia

WORKDIR /app

COPY ./res ./res
COPY ./scripts ./scripts

CMD ["python", "scripts/prepare.py"]